services:
  - docker

before_install:
- docker pull ros:kinetic-perception-xenial

script:
- echo TRAVIS_BUILD_DIR is $TRAVIS_BUILD_DIR
- docker run -v $TRAVIS_BUILD_DIR:/ros_ws/src/spinnaker_sdk_camera_driver/ ros:kinetic-perception-xenial /bin/bash -c "/ros_ws/src/spinnaker_sdk_camera_driver/download_and_install_spinnaker.sh; cd /ros_ws; catkin_make"
